name: run test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  run_test:
    name: run code test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-seq-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements-test.txt') }}

      - name: install dependencies
        run: pip install -r requirements-test.txt

      - name: test
        run: pytest
